Forum/Forum.WebMVC/Models/Posts/DisplayPostCommentsRequestModel.cs
using Forum.Models.Pagination;

namespace Forum.WebMVC.Models.Posts
{
    public class DisplayPostCommentsRequestModel : PaginationRequestModel
    {
        public long PostId { get; set; }
    }
}

Forum/Forum.WebMVC/Models/Posts/DisplayPostCommentsViewModel.cs
using Forum.Models.Request.Comment;
using Forum.Models.Response.Post;

namespace Forum.WebMVC.Models.Posts
{
    public class DisplayPostCommentsViewModel
    {
        public int Page { get; set; }

        public PostResponseModel Post { get; set; }

        public CreateCommentRequestModel Comment { get; set; }
    }
}

Forum/Forum.WebMVC/Controllers/PostsController.cs
//Local
using Forum.Models.Request.Comment;
using Forum.Models.Request.Post;
using Forum.Service.Contracts;
using Forum.WebMVC.Helpers;
using Forum.WebMVC.Models.Home;
using Forum.WebMVC.Models.Posts;
//Nuget packets
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//Public
using System.Threading.Tasks;
//Static
using static Forum.Service.Common.Message.Message;

namespace Forum.WebMVC.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService postService;
        private readonly ISelectListService selectListService;

        public PostsController(IPostService postService, ISelectListService selectListService)
        {
            this.postService = postService;
            this.selectListService = selectListService;
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> CreateForm()
        {
            ViewBag.Categories = new SelectList(await this.selectListService.GetAllCategoriesAsync(), "Id", "Name");
            return View();
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Create([FromForm] CreatePostRequestModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View("CreateForm", model);
            }

            await this.postService.CreateAsync(model);

            return this.RedirectToAction("Index", "Home", new PostSortRequestModel { MostRecently = "mr"});
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> EditForm(long id, int page)
        {
            ViewBag.Categories = new SelectList(await this.selectListService.GetAllCategoriesAsync(), "Id", "Name");
            var post = await this.postService.GetByIdAsync(id);
            ViewBag.Post = post.Payload;
            ViewBag.Page = page;
            return View();
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Edit(long id, int page, [FromForm] EditPostRequestModel model)
        {
            var userId = long.Parse(this.Request.Cookies["UserId"]);

            await this.postService.EditAsync(id, userId, model);

            return this.RedirectToAction("Index", "Home", new HomeIndexRequest() { Page = page });
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Delete(long id, int page)
        {
            long? userId = null;

            if (this.Request.Cookies["Role"].Equals(Constants.User))
            {
                userId = long.Parse(this.Request.Cookies["UserId"]);
            }

            await this.postService.DeleteAsync(id, userId);

            return this.RedirectToAction("Index", "Home", new HomeIndexRequest() { Page = page });
        }

        [HttpGet]
        public async Task<IActionResult> DisplayPostComments(DisplayPostCommentsRequestModel request)
        {
            var post = await this.postService.GetByIdAsync(request.PostId);

            var model = new DisplayPostCommentsViewModel()
            {
                Post = post.Payload,
                Page = request.Page,
                Comment = new CreateCommentRequestModel()
                {
                    PostId = request.PostId
                }
            };

            ViewBag.Page = request.Page;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Filter([FromQuery] PostFilterRequestModel request)
        {
            request.PerPage = 5;

            var result = await this.postService.FilterAsync(request);

            ViewBag.Page = request.Page;

            return View("Index", result.Payload);
        }
    }
}

Forum/Forum.WebMVC/ViewComponents/Post/DisplayUserPostsViewComponent.cs
using Forum.Models.Request.Post;
using Forum.Service.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Forum.WebMVC.ViewComponents.Post
{
    public class DisplayUserPostsViewComponent : ViewComponent
    {
        private readonly IPostService postService;
        private readonly PostFilterRequestModel request;

        public DisplayUserPostsViewComponent(IPostService postService)
        {
            this.postService = postService;
            this.request = new PostFilterRequestModel()
            {
                Page = 1,
                PerPage = 5,
                MostRecently = "mr"
            };
        }

        public async Task<IViewComponentResult> InvokeAsync(long userId)
        {
            this.request.UserId = userId;

            var result = await this.postService.FilterAsync(this.request);

            return View("DisplayPosts", result.Payload.Entities);
        }
    }
}

Forum/Forum.WebMVC/Views/Posts/CreateForm.cshtml
@model CreatePostRequestModel

@{
    ViewData["Title"] = "Post Create";
}

<div class="post">

    <form asp-controller="Posts" asp-action="Create" class="form newtopic" method="post">

        <div class="topwrap">

            <div class="userinfo pull-left">

                <div class="avatar">
                    <img src="@this.Context.Request.Cookies["Avatar"]" alt="" />
                </div>

            </div>

            <input style="display: none" type="number" name="UserId" value=@long.Parse(this.Context.Request.Cookies["UserId"]) />

            <div class="posttext pull-left">

                <!-- Title form -->
                <div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                    <input asp-for="Title" type="text" placeholder="Enter Topic Title" class="form-control" required />
                </div>

                <div class="row">
                    <!-- Category dropdown -->
                    <div class="col-lg-6 col-md-6">
                        <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories" required>
                            <option value="" disabled selected>Select Category</option>
                        </select>
                    </div>
                    <!--Sub Category dropdown optional -->

                </div>
                <!-- Description form -->
                <div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                    <textarea asp-for="Description" placeholder="Description" class="form-control" required></textarea>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="postinfobot">

            <div class="pull-right postreply">
                <div class="pull-left"><button type="submit" class="btn btn-primary">Post</button></div>
                <div class="clearfix"></div>
            </div>


            <div class="clearfix"></div>
        </div>
    </form>
</div><!-- POST -->

Forum/Forum.WebMVC/Views/Posts/DisplayPostComments.cshtml
@model DisplayPostCommentsViewModel

<partial model="@Model.Post" name="~/Views/Shared/Partials/_PostTemplatePartial.cshtml" />

@section Scripts
{
    <script asp-append-version="true" src="~/js/PostLikeAjax.js"></script>
}

@(await Component.InvokeAsync<DisplayPostCommentsViewComponent>(Model))

<partial model="@Model.Comment" name="~/Views/Shared/Partials/_CommentCreatePartial.cshtml" />

Forum/Forum.WebMVC/Views/Posts/EditForm.cshtml
@model EditPostRequestModel

@{
    ViewData["Title"] = "Post edit";
}

<div class="post">

    <form asp-controller="Posts" asp-action="Edit" asp-route-id="@ViewBag.Post.Id" asp-route-page="@ViewBag.Page" class="form newtopic" method="post">

        <div class="topwrap">

            <div class="userinfo pull-left">

                <div class="avatar">
                    <img src="@this.Context.Request.Cookies["Avatar"]" alt="" />
                </div>

            </div>

            <div class="posttext pull-left">

                <!-- Title form -->
                <div>
                    <input asp-for="Title" type="text" value="@ViewBag.Post.Title" class="form-control" />
                </div>

                <div class="row">
                    <!-- Category dropdown -->
                    <div class="col-lg-6 col-md-6">
                        <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                            <option value="" disabled selected>Select Category</option>
                        </select>
                    </div>
                    <!--Sub Category dropdown optional -->

                </div>
                <!-- Description form -->
                <div>
                    <textarea asp-for="Description" placeholder="@ViewBag.Post.Description" class="form-control"></textarea>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="postinfobot">

            <div class="pull-right postreply">
                <div class="pull-left"><button type="submit" class="btn btn-primary">Post</button></div>
                <div class="clearfix"></div>
            </div>


            <div class="clearfix"></div>
        </div>
    </form>
</div><!-- POST -->

Forum/Forum.WebMVC/Views/Posts/Index.cshtml
@model Paginate<PostResponseModel>

@foreach (var post in Model.Entities)
{
    <partial model="@post" name="~/Views/Shared/Partials/_PostTemplatePartial.cshtml" />
}

@(await Component.InvokeAsync<PagerViewComponent>(Model.Metadata))

@section Scripts
{
    <script asp-append-version="true" src="~/js/PostLikeAjax.js"></script>
}