Forum/Forum.WebMVC/Controllers/CommentLikesController.cs
//Local
using Forum.Models.Request.CommentLike;
using Forum.Service.Contracts;
using Forum.WebMVC.Helpers;
using Forum.WebMVC.Models.Posts;
//Static
using static Forum.Service.Common.Message.Message;
//Nuget Packets
using Microsoft.AspNetCore.Mvc;
//Public
using System.Threading.Tasks;

namespace Forum.WebMVC.Controllers
{
    public class CommentLikesController : Controller
    {
        private readonly ICommentLikeService commentLikeService;
        private readonly ICommentService commentService;

        public CommentLikesController(ICommentLikeService commentLikeService, ICommentService commentService)
        {
            this.commentLikeService = commentLikeService;
            this.commentService = commentService;
        }

        [HttpPost]
        [Authorization(new string[] { Constants.User, Constants.Admin, Constants.Blocked })]
        public async Task<IActionResult> Create([FromForm]CommentLikeRequestModel commentLikeRequest, long postId, int page)
        {
            commentLikeRequest.UserId = long.Parse(this.Request.Cookies["UserId"]);

            await this.commentLikeService.CreateAsync(commentLikeRequest);

           // return this.RedirectToAction("DisplayPostComments", "Posts", new DisplayPostCommentsRequestModel { PostId = postId, Page = page});

            var likesCount = await this.commentService.GetLikesCountAsync(commentLikeRequest.CommentId);

            return Ok(new { count = likesCount });
        }
    }
}

Forum/Forum.WebMVC/Controllers/CommentsController.cs
//Local
using Forum.Models.Request.Comment;
using Forum.Service.Contracts;
using Forum.WebMVC.Helpers;
using Forum.WebMVC.Models.Posts;
//Nuget packets
using Microsoft.AspNetCore.Mvc;
//Public
using System.Threading.Tasks;
//Static
using static Forum.Service.Common.Message.Message;

namespace Forum.WebMVC.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentService commentService;

        public CommentsController(ICommentService commentService)
        {
            this.commentService = commentService;
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        [HttpPost]
        public async Task<IActionResult> Create([FromForm]CreateCommentRequestModel request)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("DisplayPostComments", "Posts", new DisplayPostCommentsRequestModel() { PostId = request.PostId });
            }

            await this.commentService.CreateAsync(request);

            return this.RedirectToAction("DisplayPostComments", "Posts" , new DisplayPostCommentsRequestModel() { PostId = request.PostId});
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> EditForm(long id)
        {
            var comment = await this.commentService.GetByIdAsync(id);
            ViewBag.Comment = comment.Payload;
            return View();
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Edit(long id,[FromForm]EditCommentRequestModel model)
        {
            var userId = long.Parse(this.Request.Cookies["UserId"]);

            await this.commentService.EditAsync(id, userId, model);

            return this.RedirectToAction("Index", "Home");
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Delete (long id, long postId)
        {
            long? userId = null;

            if (this.Request.Cookies["Role"].Equals(Constants.User))
            {
                userId = long.Parse(this.Request.Cookies["UserId"]);
            }

            await this.commentService.DeleteAsync(id, userId);

            return this.RedirectToAction("DisplayPostComments", "Posts", new DisplayPostCommentsRequestModel() { PostId = postId });
        }
    }
}

Forum/Forum.WebMVC/Controllers/PostLikesController.cs
//Local
using Forum.Models.Request.PostLike;
using Forum.Service.Contracts;
using Forum.WebMVC.Helpers;
using Forum.WebMVC.Models.Home;
//Nuget packets
using Microsoft.AspNetCore.Mvc;
//Public
using System.Threading.Tasks;
//Static
using static Forum.Service.Common.Message.Message;

namespace Forum.WebMVC.Controllers
{
    public class PostLikesController : Controller
    {
        private readonly IPostLikeService postLikeService;
        private readonly IPostService postService;

        public PostLikesController(IPostLikeService postLikeService,
              IPostService postService)
        {
            this.postLikeService = postLikeService;
            this.postService = postService;
        }

        [HttpPost]
        [Authorization(new string[] { Constants.User, Constants.Admin, Constants.Blocked })]
        public async Task<IActionResult> Create([FromForm] PostLikeRequestModel postLikeRequest)
        {
            postLikeRequest.UserId = long.Parse(this.Request.Cookies["UserId"]);

            await this.postLikeService.CreateAsync(postLikeRequest);

            var likesCount = await this.postService.GetLikesCountAsync(postLikeRequest.PostId);

            return Ok(new { count = likesCount });
        }
    }
}

Forum/Forum.WebMVC/Controllers/PostsController.cs
//Local
using Forum.Models.Request.Comment;
using Forum.Models.Request.Post;
using Forum.Service.Contracts;
using Forum.WebMVC.Helpers;
using Forum.WebMVC.Models.Home;
using Forum.WebMVC.Models.Posts;
//Nuget packets
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//Public
using System.Threading.Tasks;
//Static
using static Forum.Service.Common.Message.Message;

namespace Forum.WebMVC.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService postService;
        private readonly ISelectListService selectListService;

        public PostsController(IPostService postService, ISelectListService selectListService)
        {
            this.postService = postService;
            this.selectListService = selectListService;
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> CreateForm()
        {
            ViewBag.Categories = new SelectList(await this.selectListService.GetAllCategoriesAsync(), "Id", "Name");
            return View();
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Create([FromForm] CreatePostRequestModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View("CreateForm", model);
            }

            await this.postService.CreateAsync(model);

            return this.RedirectToAction("Index", "Home", new PostSortRequestModel { MostRecently = "mr"});
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> EditForm(long id, int page)
        {
            ViewBag.Categories = new SelectList(await this.selectListService.GetAllCategoriesAsync(), "Id", "Name");
            var post = await this.postService.GetByIdAsync(id);
            ViewBag.Post = post.Payload;
            ViewBag.Page = page;
            return View();
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Edit(long id, int page, [FromForm] EditPostRequestModel model)
        {
            var userId = long.Parse(this.Request.Cookies["UserId"]);

            await this.postService.EditAsync(id, userId, model);

            return this.RedirectToAction("Index", "Home", new HomeIndexRequest() { Page = page });
        }

        [Authorization(new string[] { Constants.User, Constants.Admin })]
        public async Task<IActionResult> Delete(long id, int page)
        {
            long? userId = null;

            if (this.Request.Cookies["Role"].Equals(Constants.User))
            {
                userId = long.Parse(this.Request.Cookies["UserId"]);
            }

            await this.postService.DeleteAsync(id, userId);

            return this.RedirectToAction("Index", "Home", new HomeIndexRequest() { Page = page });
        }

        [HttpGet]
        public async Task<IActionResult> DisplayPostComments(DisplayPostCommentsRequestModel request)
        {
            var post = await this.postService.GetByIdAsync(request.PostId);

            var model = new DisplayPostCommentsViewModel()
            {
                Post = post.Payload,
                Page = request.Page,
                Comment = new CreateCommentRequestModel()
                {
                    PostId = request.PostId
                }
            };

            ViewBag.Page = request.Page;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Filter([FromQuery] PostFilterRequestModel request)
        {
            request.PerPage = 5;

            var result = await this.postService.FilterAsync(request);

            ViewBag.Page = request.Page;

            return View("Index", result.Payload);
        }
    }
}

Forum/Forum.WebMVC/Views/Shared/Partials/_CommentCreatePartial.cshtml
@model CreateCommentRequestModel

<div class="post">

    <form asp-controller="Comments" asp-action="Create" class="form newtopic" method="post">

        <div class="topwrap">

            <div class="userinfo pull-left">

                <div class="avatar">

                    @if (this.Context.Request.Cookies.Any(c => c.Key == "Role"))
                    {
                        <img src="@this.Context.Request.Cookies["Avatar"]" alt="" />
                    }
                    else
                    {
                        <img src="@Message.Constants.Default_Avatar" />
                    }

                </div>

            </div>

            <input style="display: none" type="number" name="PostId" value=@Model.PostId />

            <input style="display: none" type="number" name="UserId" value=@long.Parse(this.Context.Request.Cookies["UserId"]) />

            <div class="posttext pull-left">

                <div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                    <textarea asp-for="Description" placeholder="Description" class="form-control" required></textarea>
                </div>

            </div>

            <div class="clearfix"></div>

        </div>

        <div class="postinfobot">

            <div class="pull-right postreply">
                <div class="pull-left"><button type="submit" class="btn btn-primary">Comment</button></div>
                <div class="clearfix"></div>
            </div>

            <div class="clearfix"></div>
        </div>
    </form>
</div><!-- POST -->

Forum/Forum.WebMVC/Views/Shared/Partials/_CommentTemplatePartial.cshtml
@model CommentResponseModel

<div class="post">

    <div class="wrap-ut pull-left">

        <div class="userinfo pull-left">

            <div class="avatar">

                <img src=@Model.Avatar />
                @if (this.Context.Request.Cookies.Any(c => c.Key == "UserId") && (long.Parse(this.Context.Request.Cookies["UserId"]).Equals(Model.UserId) || this.Context.Request.Cookies["Role"].Equals("Admin")))
                {
                    <div class="views dropdown">

                        <a data-toggle="dropdown" href="#"><i class="fa fa-ellipsis-h"></i></a>

                        <ul class="dropdown-menu" role="menu">

                            <li role="presentation"><a role="menuitem" tabindex="-1" asp-controller="Comments" asp-action="EditForm" asp-route-id="@Model.Id" asp-route-postId="@Model.PostId">Edit</a></li>

                            <li role="presentation"><a role="menuitem" tabindex="-3" asp-controller="Comments" asp-action="Delete" asp-route-id="@Model.Id" asp-route-postId="@Model.PostId">Delete</a></li>

                        </ul>

                    </div>
                }

            </div>

        </div>

        <div class="posttext pull-left">

            <span><a asp-controller="Posts" asp-action="Filter" asp-route-username=@Model.Username>@Model.Username</a></span>

            <p>@Model.Description</p>

        </div>

        <div class="clearfix"></div>

    </div>

    <div class="time"><i class="fa fa-clock-o"></i> Days: @(DateTime.UtcNow.Subtract(Model.CreatedOn).Days)</div>

    <div class="clearfix"></div>

    <div class="postinfobot">

        <div class="likeblock pull-left">
            <form asp-controller="CommentLikes" asp-action="Create" method="post" onsubmit="return LikeCommentAjax(this, @Model.Id)">

                <input style="display: none" type="text" name="UserId" value="@Model.UserId" />
                <input style="display: none" type="text" name="CommentId" value="@Model.Id" />

                <div class="">
                    <button id="like-button1" class="likes-count up" type="submit"><i class="fa fa-thumbs-o-up"></i></button>
                    <span id="likesC-@Model.Id" type="text" name="name">@Model.Likes</span>
                </div>

            </form>

        </div>

            <div class="posted pull-right"><i class="fa fa-clock-o"></i>Created On: @Model.CreatedOn</div>

            <div class="clearfix"></div>

        </div>

</div>

<style>
    #like-button1 {
        outline: none;
        background: none;
        border: none;
    }
</style>

Forum/Forum.WebMVC/Views/Shared/Partials/_FilterAndOrderCard.cshtml
<form asp-controller="Posts" asp-action="Filter" method="get">
    <div class="sidebarblock">

        <h3>Filter &amp; Sort</h3>

        <div class="divline"></div>

        <div class="blocktxt">

            <ul class="cats">

                <li> <input class="form-control" type="text" name="Title" placeholder="Type Title" /> </li>
                <br>
                <li> <input class="form-control" type="text" name="Category" placeholder="Type Category" /> </li>
                <br>
                <li> <input class="form-control" type="text" name="Description" placeholder="Type Description" /> </li>
                <br>
                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="MostRecently" value="mr" id="flexCheckDefault">
                        <span class="badge">Most Recently</span>
                    </div>
                </li>

                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="MostLiked" value="ml" id="flexCheckDefault">
                        <span class="badge">Most Liked</span>
                    </div>
                </li>

                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="MostCommented" value="mc" id="flexCheckDefault">
                        <span class="badge">Most Commented</span>
                    </div>
                </li>

                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="TitleAsc" value="ta" id="flexCheckDefault">
                        <span class="badge">Title ASC</span>
                    </div>
                </li>

                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="TitleDes" value="td" id="flexCheckDefault">
                        <span class="badge">Title DES</span>
                    </div>
                </li>
                <br>
                <li>
                    <input class="btn btn-primary" type="submit" value="Apply" />
                </li>

            </ul>

        </div>

    </div>

</form>

Forum/Forum.WebMVC/Views/Shared/Partials/_PostTemplatePartial.cshtml
@model PostResponseModel

<div class="post">

    <div class="wrap-ut pull-left">

        <div class="userinfo pull-left">

            <div class="avatar">
                <a asp-controller="Posts" asp-action="Filter" asp-route-username=@Model.Username><img src=@Model.Avatar /></a>
            </div>

        </div>

        <div class="posttext pull-left">

            <span><a asp-controller="Posts" asp-action="Filter" asp-route-username=@Model.Username>@Model.Username</a></span>

            <h2><a asp-controller="Posts" asp-action="DisplayPostComments" asp-route-postId="@Model.Id">@Model.Title</a></h2>
            <p>@Model.Description</p>

        </div>

        <div class="clearfix"></div>

    </div>

    <div class="postinfo pull-left">

        <div class="comments">

            <div class="commentbg">

                @Model.CommentCount

                <div class="mark"></div>

            </div>

        </div>

        @if (this.Context.Request.Cookies.Any(c => c.Key == "UserId") && (long.Parse(this.Context.Request.Cookies["UserId"]).Equals(Model.UserId) || this.Context.Request.Cookies["Role"].Equals("Admin")))
        {
            <div class="views dropdown">

                <a data-toggle="dropdown" href="#"><i class="fa fa-ellipsis-h"></i></a>

                <ul class="dropdown-menu" role="menu">

                    <li role="presentation"><a role="menuitem" tabindex="-1" asp-controller="Posts" asp-action="EditForm" asp-route-id="@Model.Id" asp-route-page="@ViewBag.Page">Edit</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-3" asp-controller="Posts" asp-action="Delete" asp-route-id="@Model.Id" asp-route-page="@ViewBag.Page">Delete</a></li>

                </ul>

            </div>
        }

        <div class="time"><i class="fa fa-clock-o"></i> Days: @(DateTime.UtcNow.Subtract(Model.CreatedOn).Days)</div>

        <div class="time">
            <span><a asp-controller="Posts" asp-action="Filter" asp-route-category=@Model.Category>@Model.Category</a></span>
        </div>

    </div>

    <div class="clearfix"></div>

    <div class="postinfobot">

        <div class="likeblock pull-left">

            <form asp-controller="PostLikes" asp-action="Create" method="post" onsubmit="return LikePostAjax(this, @Model.Id)">

                <input style="display: none" type="text" name="UserId" value="@Model.UserId" />
                <input style="display: none" type="text" name="PostId" value="@Model.Id" />

                <div class="">

                    <button id="like-button" class="likes-count up" type="submit"><i class="fa fa-thumbs-o-up"></i></button>
                    <span id="likesP-@Model.Id" type="text" name="name"> @Model.LikesCount</span>

                </div>

            </form>

        </div>

        <div class="posted pull-right"><i class="fa fa-clock-o"></i>Created On: @Model.CreatedOn</div>

        <div class="clearfix"></div>

    </div>

</div>

<style>
    #like-button {
        outline: none;
        background: none;
        border: none;
    }
</style>

Forum/Forum.WebMVC/Views/Shared/Partials/_Profiles.cshtml
@model Forum.Models.Response.User.UserResponseModel


<div class="post">

    <div class="postinfotop">
        <h2>User Profile</h2>
    </div>

    <!-- acc section -->
    <div class="accsection">
        <div class="topwrap">
            <div class="userinfo pull-left">
                <div class="avatar">
                    <img id="img" src="@Model.PicturePath" alt="Avatar">
                </div>
            </div>
            <div class="posttext pull-left">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <span>Email:</span>
                        <p>@Model.Email</p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <span>Username:</span>
                        <p>@Model.UserName</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <span>Display name:</span>
                        <p>@Model.DisplayName</p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <span>Role:</span>
                        @if (Model.Role == "User")
                        {
                            <p style="color:green">@Model.Role</p>
                        }
                        else if (Model.Role == "Pending")
                        {
                            <p style="color:orange">@Model.Role</p>
                            <span>Check email to complete Registration!</span>
                            <div><a asp-controller="Account" asp-action="ResendEmail" asp-route-email="@ViewBag.CurrentUser.Email" asp-route-code="@ViewBag.CurrentUser.Code">Send validation link</a></div>
                        }
                        else if (Model.Role == "Blocked")
                        {
                            <p style="color:red">@Model.Role</p>
                        }
                        else if (Model.Role == "Admin")
                        {
                            <p style="color:blue">@Model.Role</p>
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <p><a asp-controller="Posts" asp-action="Filter" asp-route-username=@Model.UserName>All posts</a></p>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <p>@Model.PostsCount</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div><!-- acc section END -->

    <div class="postinfobot">
        <div class="pull-right postreply">
            @if (Model.Role == "Blocked")
            {
                <div class="pull-left">
                    <form asp-controller="Admin" asp-action="Unblock" method="post">
                        <input style="display: none" type="text" name="Id" value="@Model.Id" />
                        <input type="submit" class="btn btn-success" name="name" value="Unblock" />
                    </form>
                </div>
            }
            else
            {
                <form asp-controller="Admin" asp-action="Block" method="post">
                    <div class="pull-left">
                        <input style="display: none" type="text" name="Id" value="@Model.Id" />
                        <input type="submit" class="btn btn-danger" name="name" value="Block" />
                    </div>
                </form>
            }
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>